# Generated by Django 5.0.6 on 2025-02-02 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción')),
                ('precio_unit', models.FloatField(verbose_name='P. Unitario')),
                ('precio_media', models.FloatField(blank=True, null=True, verbose_name='P. Media')),
                ('precio_doc', models.FloatField(blank=True, null=True, verbose_name='P. Docena')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.productocategoria', verbose_name='Categoría')),
            ],
        ),
        migrations.CreateModel(
            name='Insumos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('precio', models.FloatField(verbose_name='Precio')),
                ('unidad', models.CharField(choices=[('Kg', 'Kg'), ('Gr', 'Gr'), ('Ltr', 'Ltr'), ('Unid', 'Unid'), ('Doc', 'Doc'), ('Caja', 'Caja'), ('Pack', 'Pack'), ('Lata', 'Lata'), ('Rollo', 'Rollo')], max_length=50)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.proveedores', verbose_name='Proveedor')),
            ],
        ),
    ]
