# Generated by Django 5.0.6 on 2025-02-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_productoinsumos'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_rec',
            field=models.FloatField(default=1, verbose_name='Precio Recomendado'),
        ),
    ]
