# Generated by Django 5.1.5 on 2025-01-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_alter_producto_precio_doc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productocategoria',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
