# Generated by Django 5.0.6 on 2025-02-12 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_alter_insumos_unidad_alter_productoinsumos_unidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoinsumos',
            name='producto_insumo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos_insumo', to='productos.producto', verbose_name='Producto Insumo'),
        ),
    ]
