# Generated by Django 5.0.6 on 2025-02-12 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_productoinsumos_producto_insumo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoinsumos',
            name='producto_insumo',
        ),
    ]
