# Generated by Django 5.0.6 on 2025-03-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0009_remove_productoinsumos_producto_insumo'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumos',
            name='observacion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Observación'),
        ),
    ]
