# Generated by Django 5.0.6 on 2025-04-14 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_insumos_observacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cantidad',
            field=models.IntegerField(default=99, verbose_name='Cantidad'),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.BooleanField(default=True, verbose_name='Stock'),
        ),
        migrations.AddField(
            model_name='productocategoria',
            name='cantidad',
            field=models.IntegerField(default=99, verbose_name='Cantidad'),
        ),
        migrations.AddField(
            model_name='productocategoria',
            name='stock',
            field=models.BooleanField(default=True, verbose_name='Stock'),
        ),
    ]
