# Generated by Django 5.0.6 on 2026-01-29 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0011_producto_cantidad_producto_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='cantidad',
            field=models.FloatField(default=99, verbose_name='Cantidad'),
        ),
    ]
