# Generated by Django 5.0.6 on 2026-01-30 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0012_alter_producto_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productocategoria',
            name='cantidad',
            field=models.FloatField(default=99, verbose_name='Cantidad'),
        ),
    ]
