# Generated by Django 5.0.6 on 2025-03-27 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0004_alter_facturas_envio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturas',
            name='envio',
        ),
        migrations.AddField(
            model_name='facturas',
            name='envios',
            field=models.BooleanField(default=True),
        ),
    ]
