# Generated by Django 5.0.6 on 2025-03-27 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0005_remove_facturas_envio_facturas_envios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facturas',
            old_name='envios',
            new_name='envio',
        ),
    ]
