# Generated by Django 5.0.6 on 2026-02-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0006_rename_envios_facturas_envio'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='turno',
            field=models.CharField(blank=True, choices=[('mediodia', 'Mediodía'), ('noche', 'Noche')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='facturas',
            name='turno',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='caja',
            name='estado_caja',
            field=models.BooleanField(default=False),
        ),
    ]
