# Generated by Django 5.0.6 on 2026-02-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0007_caja_turno_facturas_turno_alter_caja_estado_caja'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaproducto',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
