# Generated by Django 5.0.6 on 2026-02-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0008_facturaproducto_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturaproducto',
            name='telefono',
        ),
        migrations.AddField(
            model_name='facturas',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
