# Generated by Django 5.0.6 on 2026-02-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0009_remove_facturaproducto_telefono_facturas_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturas',
            name='direccion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='facturas',
            name='nombre',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
