# Generated by Django 5.1.5 on 2025-01-21 18:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0009_alter_facturaproducto_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturas',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
