# Generated by Django 5.0.6 on 2026-02-10 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0010_facturas_direccion_facturas_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturas',
            name='descuento',
            field=models.CharField(default=5, max_length=50),
            preserve_default=False,
        ),
    ]
