# Generated by Django 5.0.6 on 2026-02-10 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0011_facturas_descuento'),
        ('pedido', '0013_pedidosreservado_descuento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturas',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedido.pedido'),
        ),
    ]
