# Generated by Django 5.0.6 on 2026-02-10 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0012_facturas_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturas',
            name='pedido',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
