# Generated by Django 5.0.6 on 2026-02-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0013_alter_facturas_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaproducto',
            name='subtotal',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
