# Generated by Django 5.0.6 on 2026-02-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0014_facturaproducto_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaproducto',
            name='empanadas',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
