# Generated by Django 5.0.6 on 2026-02-11 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0015_facturaproducto_empanadas'),
        ('productos', '0013_alter_productocategoria_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturaproducto',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.producto'),
        ),
    ]
