# Generated by Django 5.1.5 on 2025-01-21 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Insumos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('precio', models.FloatField(verbose_name='Precio')),
                ('unidad', models.CharField(choices=[('kilogramo', 'Kg'), ('gramos', 'Gr'), ('litro', 'Ltr'), ('unidad', 'Unid'), ('docena', 'Doc'), ('caja', 'Caja'), ('pack', 'Pack'), ('lata', 'Lata'), ('rollo', 'Rollo')], max_length=50)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gastos.proveedores', verbose_name='Categoría')),
            ],
        ),
    ]
