# Generated by Django 5.1.5 on 2025-01-21 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0002_alter_insumos_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumos',
            name='unidad',
            field=models.CharField(choices=[('Kg', 'Kg'), ('Gr', 'Gr'), ('Ltr', 'Ltr'), ('Unid', 'Unid'), ('Doc', 'Doc'), ('Caja', 'Caja'), ('Pack', 'Pack'), ('Lata', 'Lata'), ('Rollo', 'Rollo')], max_length=50),
        ),
    ]
