# Generated by Django 5.1.5 on 2025-01-21 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0003_alter_insumos_unidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gastos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(verbose_name='Cantidad')),
                ('monto', models.FloatField(verbose_name='Monto')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gastos.insumos', verbose_name='Insumo')),
            ],
        ),
    ]
