# Generated by Django 5.1.5 on 2025-01-21 18:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0004_gastos'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastos',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
