# Generated by Django 5.1.5 on 2025-01-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0005_gastos_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastos',
            name='forma_pago',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
