# Generated by Django 5.1.5 on 2025-01-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0006_gastos_forma_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastos',
            name='forma_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('mercado', 'Mercado'), ('naranja', 'Naranja')], max_length=50),
        ),
    ]
