# Generated by Django 5.1.5 on 2025-01-23 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0007_alter_gastos_forma_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gastos',
            name='insumo',
        ),
        migrations.AddField(
            model_name='gastos',
            name='proveedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gastos.proveedores', verbose_name='Proveedor'),
            preserve_default=False,
        ),
    ]
