# Generated by Django 5.1.5 on 2025-01-23 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0008_remove_gastos_insumo_gastos_proveedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gastos',
            name='cantidad',
        ),
    ]
