# Generated by Django 5.1.5 on 2025-01-31 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costos', '0001_initial'),
        ('gastos', '0009_remove_gastos_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastos',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costos.proveedores', verbose_name='Proveedor'),
        ),
        migrations.DeleteModel(
            name='Insumos',
        ),
        migrations.DeleteModel(
            name='Proveedores',
        ),
    ]
