# Generated by Django 5.0.6 on 2025-02-02 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormaEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma_entrega', models.CharField(max_length=50)),
                ('precio', models.FloatField(blank=True, null=True)),
                ('envio', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Forma de entrega',
                'db_table': 'formaentrega',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('entregado', 'Entregado'), ('pendiente', 'Pendiente'), ('reservado', 'reservado'), ('cancelado', 'Cancelado')], max_length=10)),
                ('pago', models.CharField(choices=[('efectivo', 'EFT'), ('mercado', 'MP'), ('naranja', 'NRJ'), ('cobrar', 'COBRAR')], max_length=10)),
                ('precio_entrega', models.FloatField(blank=True, null=True)),
                ('hora', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('observacion', models.CharField(blank=True, max_length=100, null=True)),
                ('cantidad_emp', models.FloatField(blank=True, null=True)),
                ('subtotal_emp', models.FloatField(blank=True, null=True)),
                ('total', models.FloatField()),
                ('forma_entrega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedido.formaentrega')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'db_table': 'pedidos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PedidoProductos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(default=1)),
                ('subtotal', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedido.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
            ],
            options={
                'verbose_name': 'Producto pedido',
                'verbose_name_plural': 'Productos pedidos',
                'db_table': 'productospedidos',
                'ordering': ['id'],
            },
        ),
    ]
