# Generated by Django 5.0.6 on 2025-04-01 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
        ('productos', '0010_insumos_observacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('entregado', 'Entregado'), ('pendiente', 'Pendiente'), ('cancelado', 'Cancelado')], max_length=10),
        ),
        migrations.CreateModel(
            name='PedidosReservado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('reservado', 'Reservado'), ('entregado', 'Entregado'), ('pendiente', 'Pendiente'), ('cancelado', 'Cancelado')], default='reservado', max_length=10)),
                ('pago', models.CharField(choices=[('efectivo', 'EFT'), ('mercado', 'MP'), ('naranja', 'NRJ'), ('cobrar', 'COBRAR')], max_length=10)),
                ('precio_entrega', models.FloatField(blank=True, null=True)),
                ('hora', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('observacion', models.CharField(blank=True, max_length=100, null=True)),
                ('cantidad_emp', models.FloatField(blank=True, null=True)),
                ('subtotal_emp', models.FloatField(blank=True, null=True)),
                ('total', models.FloatField()),
                ('forma_entrega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedido.formaentrega')),
            ],
            options={
                'verbose_name': 'Pedido Reservado',
                'verbose_name_plural': 'Pedidos Reservados',
                'db_table': 'pedidos_reservados',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PedidosProductosReservados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(default=1)),
                ('subtotal', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedido.pedidosreservado')),
            ],
            options={
                'verbose_name': 'Producto Pedido Reservado',
                'verbose_name_plural': 'Productos Pedidos Reservados',
                'db_table': 'productos_pedidos_reservados',
                'ordering': ['id'],
            },
        ),
    ]
