# Generated by Django 5.0.6 on 2025-04-01 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_alter_pedido_estado_pedidosreservado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('entregado', 'Entregado'), ('pendiente', 'Pendiente'), ('reservado', 'Reservado'), ('cancelado', 'Cancelado')], max_length=10),
        ),
    ]
