# Generated by Django 5.0.6 on 2025-04-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0003_alter_pedido_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidosreservado',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
