# Generated by Django 5.0.6 on 2025-04-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0005_alter_pedido_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidosreservado',
            name='tipo',
            field=models.BooleanField(default=True),
        ),
    ]
