# Generated by Django 5.0.6 on 2025-04-04 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0006_pedidosreservado_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='tipo',
            field=models.BooleanField(default=False),
        ),
    ]
