# Generated by Django 5.0.6 on 2025-04-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0007_pedido_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='tipo',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pedidosreservado',
            name='tipo',
            field=models.IntegerField(default=2),
        ),
    ]
