# Generated by Django 5.0.6 on 2026-02-09 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0008_alter_pedido_tipo_alter_pedidosreservado_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descuentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descuento', models.CharField(max_length=50)),
                ('precio', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Descuento',
                'db_table': 'descuento',
            },
        ),
    ]
