# Generated by Django 5.0.6 on 2026-02-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0009_descuentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
