# Generated by Django 5.0.6 on 2026-02-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0010_pedido_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='descuento',
            field=models.CharField(choices=[('entregado', 'Entregado'), ('pendiente', 'Pendiente'), ('cancelado', 'Cancelado')], default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='descuento_precio',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
