# Generated by Django 5.0.6 on 2026-02-09 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0011_pedido_descuento_pedido_descuento_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='descuento',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
