# Generated by Django 5.0.6 on 2026-02-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0012_alter_pedido_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidosreservado',
            name='descuento',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='pedidosreservado',
            name='descuento_precio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedidosreservado',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
